@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant ":UIProduct_Q" as pro
participant ":Product_Q" as pro1

pro -> pro1: GET/products/{sku}/barcode128
pro1 --> pro: Product
@enduml