@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant ":UIProduct_C" as pro1
participant ":Product_C" as pro

pro1 -> pro: POST/products/create
pro --> pro1: Product
@enduml